### ISSUE TITLE
Release Build Broken for Tags

### ISSUE THREAD

**Issue by mgreter** [sass/sassc#200]
https://ci.appveyor.com/project/sass/sassc/branch/master/job/i6x2t4nb9udaqkh5

```
Error creating GitHub release: Error reading repository 'sass/sassc' releases: 401 - Unauthorized
```

**Comment by am11** [comment]
Interesting, I read @FeodorFitsner's answers in this thread: http://help.appveyor.com/discussions/problems/2168-cant-create-a-github-release and figured that I don't have access to settings view in this repo. Possibly it is because `appveyor.yml` has the token generated by me: https://github.com/sass/sassc/blob/6384870/appveyor.yml#L41.

@mgreter, could you please try:

* generating a token with your accoun: https://github.com/settings/tokens
* navigate to https://ci.appveyor.com/tools/encrypt to encrypt the token
* update the appveyor.yml

Pushing a new tag subsequently will reveal whether the issue is resolved. :)

**Comment by xzyfer** [comment]
Confirmed this is fixed following @am11's instructions.

**Comment by am11** [comment]
The unauthorized access error came back with new release: https://ci.appveyor.com/project/sass/sassc/builds/25362936/job/r7vclkl5ie1nchu6#L231. Maybe the token is not valid anymore?

**Comment by xzyfer** [comment]
I can take a look when I'm back next week
