### ISSUE TITLE
Make moves into parent directory and cannot find any targets

### ISSUE THREAD

**Issue by airways** [sass/sassc#211]
The Makefile currently provided changes directory out of the sassc checkout and tries to build the parent directory. This prevents the build from working.

```
iraway@OCULAR:~/workspace$ ls -al
total 20
drwxrwxrwx 2 iraway iraway 0 May 23 09:25 .
drwxr-xr-x 2 iraway iraway 0 May 23 11:51 ..
drwxrwxrwx 2 iraway iraway 0 May 22 22:11 astroid
drwxrwxrwx 2 iraway iraway 0 May 22 22:22 libsass
drwxrwxrwx 2 iraway iraway 0 May 23 11:46 sassc

iraway@OCULAR:~/workspace/sassc$ cat ~/.bash_profile
SASS_LIBSASS_PATH=/home/iraway/workspace/libsass

iraway@OCULAR:~/workspace$ echo $SASS_LIBSASS_PATH
/home/iraway/workspace/libsass

iraway@OCULAR:~/workspace$ cd sassc/

iraway@OCULAR:~/workspace/sassc$ make
make BUILD="static" -C /home/iraway/workspace
make[1]: Entering directory `/home/iraway/workspace'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/iraway/workspace'
make: *** [libsass-static] Error 2
```

**Comment by airways** [comment]
The issue seems to have been related to my .bash_profile not being read. Still not sure why this is the case.

I would suggest not relying on environment variables in this way, it is very un-GNU like and confusing. pkg-config should give you everything you need to do the same thing in a portable, expected way.

**Comment by xmeltrut** [comment]
+1, I'm also having this problem.

**Comment by shinenelson** [comment]
I agree that using environment variables in the shell is not really portable. It might even break down when using some shells like `csh` / `fish`.

To answer your specific problem of why the variable wasn't being available to the process that were triggered by `make`, it attributes to how the shell is being invoked. There are 4 combinations of the way the shell can be invoked, viz, login / non-login and interactive / non-interactive.

The shell uses the `$HOME/.bash_profile` for login-interactive shells which `make` doesn't qualify when it spawns up a new process. You were right to put the variable in `$HOME/.bashrc` since that is where all processes start from (PS : It is not a workaround; that is how it should be).

You can read more about which files are invoked during each kind of shell invocation in the [Bash Manual](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html).
